name: Terraform Workflow

on:
  push:
    branches:
    - main
permissions:
  id-token: write # Allow the workflow to request OIDC tokens
  contents: read # Allow the workflow to access the repository contents  


jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4 # Latest version as of now        
        with:        
          role-to-assume: arn:aws:iam::014498661566:role/GHE-AWS-OIDC-ROLE       
          role-session-name: github-actions-session        
          aws-region: us-east-1

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Terraform Init with Migration Check
        run:          
            terraform init          

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan

      # - name: Terraform Destroy
      #   run: terraform destroy -auto-approve